using System;
namespace ELearningMobieApp.Helpers;

// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
// If you change the class to 'public' in order to use it outside its assembly
//  you should also change the fields from 'const' to 'public static readonly'
public static class SearchIcon
{
    public const string Search = "\ue905";
}

